### PR TITLE
Let's create a testing firmware

### PR DESCRIPTION
**Pull request by SISheogorath**
We should speed up the testingstate a bit to get closer to the new stable so we can switch to the new gatewayservers.

### CODE REVIEW

**Comment by fooker** [comment]
We should speed up fixing the bugs in development before we create testing instances containing bugs we already know.

**Comment by SISheogorath** [comment]
Can you name some of them?

**Comment by fooker** [comment]
Everything that's marked as milestone 'Firmware v3': https://github.com/freifunk-fulda/orga/milestones/Firmware%20v3

**Comment by mortzel** [comment]
The only Bug that is still open for 'Firmware v3' is https://github.com/freifunk-fulda/orga/issues/84 wich should be fixed by pull request #14 .
So we need to merge this pull request first befor pushing devlopment to testing.

**Pull request merged**
