### PR TITLE
Added migration script to change SSID and BSSID of mesh interfaces

### PR DESCRIPTION
**Pull request by fooker**
As described by https://github.com/freifunk-fulda/orga/issues/7 and https://github.com/freifunk-fulda/orga/issues/75.

### CODE REVIEW

**Comment by mortzel** [comment]
If i try to run the scipt on a WDR4300 manuel i get the following error:

```
/usr/bin/lua: ./mesh-ssid:17: bad argument #1 to 'commit' (string expected, got no value)
stack traceback:
    [C]: in function 'commit'
    ./mesh-ssid:17: in main chunk
    [C]: ?
```

**Comment by fooker** [comment]
Good catch. Fixed.

**Comment by mortzel** [comment]
After upgrade form stable-2 and development-xxx to issue-7 there ist no link at `/var/gluon/migrations/`. Even the folder does not exists. So the upgrade script `999-migration` was not called. If i call this script manuel the folder is created, but there is no link in the folder.

System: WDR4300 v1,  WR841N v9
Firmware issue-7 - build 187

**Comment by mortzel** [comment]
If i put the link in the `/var/gluon/migrations/` folder and call `migrator` the link in the folder is deleted, but the mesh settings hasn't been changed.

System: WDR4300 v1, WR841N v9
Firmware: issue-7 - build 187

**Comment by mortzel** [comment]
`/var` is a temporary folder. So the script should be there

**Comment by mortzel** [comment]
The mesh SSID will be renamed by the transasition to 802.11s

**Pull request closed without merging**
