### PR TITLE
Create stable Firmware v3.0

### PR DESCRIPTION
**Pull request by SISheogorath**
We should start greate the new stable firmware. Testing-Firmware is running without any reported firmware related issues.

We have to fix the merge confict and first merge the fffd-packages to be also in stable version. 

Then build and sign the new firmware

### CODE REVIEW

**Comment by mortzel** [comment]
Routing on gw03 should be fixed first or firmware.services.fffd is not reachable from gw03

**Comment by fooker** [comment]
AFAIK there is not very much feedback from non-firmware developers. We should ask for this first.

There are some tests bobbling around in my mind which I would like to do before we merge.

**Comment by reissmann** [comment]
This is not an issue with routing on the gateway, but an issue with the default route on srv1

**Comment by SISheogorath** [comment]
@fooker can we please document those tests, if they are not only specific for this firmware version? I think it would be useful writing a "check script" which can reused by the next upgrade.

Also it would be nice for test it on different Hardware.

**Comment by fooker** [comment]
I'm thinking abou thos since month. We've already diskussed this on the last meetings and it seems to be a very complex task.

I think we should not wait for such a test bed for this release.

Finding the test cases is kind a creative process. If you would like to start such a list, feel free to do so.

**Pull request merged**
